spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.56.128:2181
  protocol:
    port: -1
    name: dubbo
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml